# Copyright (C) 2025 Dan Novischi. All rights reserved.
# This software may be modified and distributed under the terms of the
# GNU Lesser General Public License v3 or any later version.

/**:
  ros__parameters:
    rdrive:
      wheel_radius: 0.03
      wheel_separation: 0.215
      encoder_cpr_left: 2940
      encoder_cpr_right: 2940
    rplidar:
      serial_port: "/dev/ttyUSB0"
      serial_baudrate: 115200  # For A1, you can use 256000 for A2
      frame_id: "laser"
      inverted: false
      angle_compensate: true
      scan_mode: "Sensitivity"  # Options: "Standard", "Express", "Boost", "Sensitivity"
    tf_static:
      transforms:
        - parent_frame: "base_footprint"
          child_frame: "base_link"
          translation: [0.0, 0.0, 0.2]  # base_link (wheel_base) is 0.2m above base_footprint (at ground level)
          rotation: [0.0, 0.0, 0.0]
        - parent_frame: "base_link"
          child_frame: "laser"
          translation: [0.0, 0.0, 0.1]  # laser (Lidar link) is 0.1m above base_link (wheel_base)
          rotation: [0.0, 0.0, 0.0]  
