# Copyright (C) 2025 Dan Novischi. All rights reserved.
# This software may be modified and distributed under the terms of the
# GNU Lesser General Public License v3 or any later version.
keyboard_teleoperation_node:
  ros__parameters:
    key_mapping:
      forward: ['w']
      backward: ['s']
      left: ['a']
      right: ['d']
      stop: [' ']
    max_linear_velocity: 0.4
    max_angular_velocity: 1.57
    linear_step_size: 0.05
    angular_step_size: 0.2
    target_linear_velocity: 0.0
    target_angular_velocity: 0.0
    timer_freq: 0.5

# keyboard_teleoperation:
